In [1]:
# https://github.com/aladdinpersson/Machine-Learning-Collection/blob/master/ML/TensorFlow/Basics/tutorial2-tensorbasics.py

import os
import tensorflow as tf
from tensorflow import keras

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

In [2]:
# initialization
x = tf.constant(4, shape=(1, 1))
print(x)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [3]:
x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [4]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [5]:
x = tf.ones(4, 3)
print(x)

tf.Tensor([1 1 1 1], shape=(4,), dtype=int32)


In [6]:
x = tf.zeros(3, 2, 5)
print(x)

tf.Tensor([0. 0. 0.], shape=(3,), dtype=float64)


In [7]:
x = tf.random.uniform((2, 2), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.9444634  0.6233181 ]
 [0.01052463 0.2846681 ]], shape=(2, 2), dtype=float32)


In [8]:
x = tf.random.normal((3, 3), mean=0, stddev=1)
print(tf.cast(x, dtype=tf.float64))

tf.Tensor(
[[-0.049034    1.08904994 -0.7836501 ]
 [ 0.21522136 -1.2587899   0.49251187]
 [-1.03495002 -0.18590942  0.45322329]], shape=(3, 3), dtype=float64)


In [9]:
x = tf.range(9)
x = tf.range(start=0, limit=10, delta=2)
print(x)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [10]:
# math
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

# z = tf.add(x, y)
z = x + y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [11]:
# z = tf.subtract(x, y)
z = x - y
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [12]:
# z = tf.divide(x, y)
z = x / y
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [13]:
# z = tf.multiply(x, y)
z = x * y
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [14]:
z = tf.tensordot(x, y, axes=1)
print(z)
z = tf.tensordot(x, y, axes=0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(
[[ 9  8  7]
 [18 16 14]
 [27 24 21]], shape=(3, 3), dtype=int32)


In [15]:
z = x ** 5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [16]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 2))
# matrix multiplication
z = tf.matmul(x, y)
# special operator for this
z = x @ y
print(z)

tf.Tensor(
[[ 3.1485636  -1.4830879 ]
 [ 0.77625966 -4.6805153 ]], shape=(2, 2), dtype=float32)


In [17]:
# indexing
x = tf.constant([0, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

tf.Tensor([0 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 1 2 3], shape=(6,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([0 2 1 3], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 0], shape=(7,), dtype=int32)


In [18]:
indices = tf.constant([0, 3])
x_indices = tf.gather(x, indices)
print(x_indices)

tf.Tensor([0 3], shape=(2,), dtype=int32)


In [19]:
x = tf.constant([[1, 2], [3, 4], [5, 6]])
print(x[0, :])
print(x[0:2, :])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [20]:
# reshaping
x = tf.range(9)
print(x)

x = tf.reshape(x, (3, 3))
print(x)

x = tf.transpose(x, perm=[1, 0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
