In [1]:
# https://github.com/patrickloeber/pytorchTutorial
# https://github.com/patrickloeber/pytorchTutorial/blob/master/02_tensor_basics.py

import torch

In [2]:
# Everything in pytorch is based on Tensor operations.
# A tensor can have different dimensions
# so it can be 1d, 2d, or even 3d and higher

# scalar, vector, matrix tensor

# torch.empty(size): uninitialized
x = torch.empty(1) # scalar
x

tensor([0.])

In [3]:
x = torch.empty(3) # vector, 1D
x

tensor([0., 0., 0.])

In [4]:
x = torch.empty(2, 3) # matrix, 2D
x

tensor([[-1.5940e+14,  7.3008e-43, -1.5940e+14],
        [ 7.3008e-43, -1.5927e+14,  7.3008e-43]])

In [5]:
x = torch.empty(2, 2, 3) # tensor, 3 dimensions
x

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [6]:
x = torch.empty(2, 2, 2, 3) # tensor, 4 dimensions
x

tensor([[[[-1.3570e+14,  7.3008e-43, -1.3570e+14],
          [ 7.3008e-43, -1.3751e+14,  7.3008e-43]],

         [[-1.3751e+14,  7.3008e-43, -1.3749e+14],
          [ 7.3008e-43, -1.3749e+14,  7.3008e-43]]],


        [[[-1.3742e+14,  7.3008e-43, -1.3742e+14],
          [ 7.3008e-43, -1.3750e+14,  7.3008e-43]],

         [[-1.3750e+14,  7.3008e-43, -1.4085e+14],
          [ 7.3008e-43, -1.4085e+14,  7.3008e-43]]]])

In [7]:
# torch.rand(size), random numbers [0, 1]
x = torch.rand(5, 3)
x

tensor([[0.2232, 0.3514, 0.4644],
        [0.3174, 0.6968, 0.4841],
        [0.2987, 0.7595, 0.8872],
        [0.0915, 0.7816, 0.4025],
        [0.1072, 0.6597, 0.1442]])

In [8]:
x.size()

torch.Size([5, 3])

In [9]:
x.dtype

torch.float32

In [10]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

In [11]:
x.dtype

torch.float16

In [12]:
# construct fro data
x = torch.tensor([5.5, 3])
x.size()

torch.Size([2])

In [13]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you wnat to optimize
x = torch.tensor([5.5, 3], requires_grad=True)

In [14]:
# Operations
x = torch.rand(2, 2)
y = torch.rand(2, 2)

In [15]:
# elementwise addition
z = x + y
# z = torch.add(x, y)
z

tensor([[1.4636, 1.5863],
        [0.4283, 0.6647]])

In [16]:
# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
y.add_(x)
y

tensor([[1.4636, 1.5863],
        [0.4283, 0.6647]])

In [17]:
# subtraction
z = x - y
# z = torch.sub(x, y)
z

tensor([[-0.7627, -0.7013],
        [-0.0668, -0.5332]])

In [18]:
# multiplication
z = x * y
# z = torch.mul(x, y)
z

tensor([[1.0258, 1.4039],
        [0.1549, 0.0874]])

In [19]:
# division
z = x / y
# z = torch.div(x, y)
z

tensor([[0.4789, 0.5579],
        [0.8442, 0.1979]])

In [20]:
# Slicing
x = torch.rand(5, 3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1, 1]) # element at 1, 1

tensor([[0.1622, 0.0157, 0.3833],
        [0.4708, 0.2436, 0.7314],
        [0.5976, 0.3064, 0.4728],
        [0.7526, 0.8395, 0.1553],
        [0.3068, 0.3988, 0.5965]])
tensor([0.1622, 0.4708, 0.5976, 0.7526, 0.3068])
tensor([0.4708, 0.2436, 0.7314])
tensor(0.2436)


In [21]:
# Get the actual value if only 1 element in your tensor
x[1, 1].item()

0.24361032247543335

In [22]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
# if-1 it pytorch will automatically determin the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [23]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice verse is very easy
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [24]:
# torch to numpy with .numpy()
b = a.numpy()
print(b)
type(b)

[1. 1. 1. 1. 1.]


numpy.ndarray

In [25]:
# Careful: If the Tensor is one the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [26]:
# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [27]:
# again be careful when modifying
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [28]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")        # a CUDA device object
    y = torch.ones_like(x, device=device) # directy create a tensor on GPU
    z = x + y                            # or just use strings ``.to("cuda")``
    # z = z.numpy() # not possibe because numpy cannot handle GPU tensors
    # move to CPU again
    z.to("cpu")    # ``.to`` can also change dtype together!
    # z = z.numpy()