In [1]:
import numpy as np
my_ex1 = np.array([5, 15, 25, 35])
my_ex2 = np.array([7, 14, 21, 28])
combine = np.add(my_ex1, my_ex2)
print(f"my_ex1: {my_ex1}\nmy_ex2: {my_ex2}\ncombined: {combine}")

my_ex1: [ 5 15 25 35]
my_ex2: [ 7 14 21 28]
combined: [12 29 46 63]


In [2]:
array1 = np.arange(9, 90, 3)
array1

array([ 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57,
       60, 63, 66, 69, 72, 75, 78, 81, 84, 87])

In [3]:
print(f"{combine.shape}\n{combine.dtype}")

(4,)
int64


In [4]:
import numpy as np
array2 = np.arange(50).reshape((10, 5))
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [5]:
array2.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [6]:
array3 = np.arange(50).reshape((5, 5, 2))
array3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])